// This file is generated by Sapper — do not edit it!
export const timestamp = 1616955168951;

export const files = [
	"/service-worker-index.html",
	"/bootstrap.min.css",
	"/dist/bootstrap.min.css",
	"/favicon.png",
	"/global.css",
	"/homepage-hero-1.png",
	"/horizontal_lockup.png",
	"/logo-192.png",
	"/logo-512.png",
	"/manifest.json"
];
export { files as assets }; // legacy

export const shell = [
	"/client/client.843ce0b3.js",
	"/client/inject_styles.5607aec6.js",
	"/client/index.af89c7c0.js",
	"/client/prismic-javascript.c08e41d5.js",
	"/client/contact-submitted.fc38fc68.js",
	"/client/contact.2abfe336.js",
	"/client/about.5c7a9154.js",
	"/client/sapper-dev-client.1e7a4a5e.js"
];

export const routes = [
	{ pattern: /^\/$/ },
	{ pattern: /^\/contact-submitted\/?$/ },
	{ pattern: /^\/contact\/?$/ },
	{ pattern: /^\/about\/?$/ }
];