// This file is generated by Sapper — do not edit it!
import * as component_0 from "../../../routes/index.svelte";
import * as component_1 from "../../../routes/contact-submitted.svelte";
import * as component_2 from "../../../routes/contact.svelte";
import * as component_3 from "../../../routes/about.svelte";
import * as root_comp from "../../../routes/_layout.svelte";
import error from "../../../routes/_error.svelte";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		
	],

	pages: [
		{
			// index.svelte
			pattern: /^\/$/,
			parts: [
				{ name: "index", file: "index.svelte", component: component_0 }
			]
		},

		{
			// contact-submitted.svelte
			pattern: /^\/contact-submitted\/?$/,
			parts: [
				{ name: "contact$45submitted", file: "contact-submitted.svelte", component: component_1 }
			]
		},

		{
			// contact.svelte
			pattern: /^\/contact\/?$/,
			parts: [
				{ name: "contact", file: "contact.svelte", component: component_2 }
			]
		},

		{
			// about.svelte
			pattern: /^\/about\/?$/,
			parts: [
				{ name: "about", file: "about.svelte", component: component_3 }
			]
		}
	],

	root_comp,
	error
};

export const build_dir = "__sapper__/dev";

export const src_dir = "src";

export const dev = true;