// This file is generated by Sapper — do not edit it!
// webpack does not support export * as root_comp yet so do a two line import/export
import * as root_comp from '../../../routes/_layout.svelte';
export { root_comp };
export { default as ErrorComponent } from '../../../routes/_error.svelte';

export const ignore = [];

export const components = [
	{
		js: () => import("../../../routes/index.svelte")
	},
	{
		js: () => import("../../../routes/contact-submitted.svelte")
	},
	{
		js: () => import("../../../routes/contact.svelte")
	},
	{
		js: () => import("../../../routes/about.svelte")
	}
];

export const routes = [
	{
		// index.svelte
		pattern: /^\/$/,
		parts: [
			{ i: 0 }
		]
	},

	{
		// contact-submitted.svelte
		pattern: /^\/contact-submitted\/?$/,
		parts: [
			{ i: 1 }
		]
	},

	{
		// contact.svelte
		pattern: /^\/contact\/?$/,
		parts: [
			{ i: 2 }
		]
	},

	{
		// about.svelte
		pattern: /^\/about\/?$/,
		parts: [
			{ i: 3 }
		]
	}
];

if (typeof window !== 'undefined') {
	import("C:/Users/Savannah Joyner/Desktop/mapscout-homepage/homepage/node_modules/sapper/sapper-dev-client.js").then(client => {
		client.connect(10001);
	});
}